model_list:
  - model_name: gpt-5.2-codex
    litellm_params:
      model: openai/gpt-5.2-codex
      api_key: os.environ/WOKA_API_KEY
      api_base: os.environ/WOKA_API_BASE_URL
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/WOKA_API_KEY
      api_base: os.environ/WOKA_API_BASE_URL
  - model_name: claude-opus-4-5-20251101
    litellm_params:
      model: openai/claude-opus-4-5-20251101
      api_key: os.environ/WOKA_API_KEY
      api_base: os.environ/WOKA_API_BASE_URL
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: openai/gemini-3-pro-preview
      api_key: os.environ/WOKA_API_KEY
      api_base: os.environ/WOKA_API_BASE_URL

litellm_settings:
  drop_params: true
